#spring.application.name=fc-board-work
debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    org.fc.fcboardwork: debug
    org.springframework.web.servlet: debug
    # Spring Boot 3.x Hibernate 로깅 설정
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.orm.jdbc.extract: debug
    org.springframework.orm.jpa: debug
    org.springframework.transaction: debug

spring:
#application.name: fc-board-work
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: jay
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
      defer-datasource-initialization: true
      hibernate:
        ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          default_batch_fetch_size: 100
          use_sql_comments: true  # SQL 주석 추가
          generate_statistics: true  # 통계 정보 생성

#  h2:
#    console:
#      enabled: false

  sql:
    init:
      mode: always

  data.rest:
    base-path: /api
    detection-strategy: annotated

---

#spring:
#  config:
#    activate:
#      on-profile: testdb
#
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql.init.mode: always
#  test.database.replace: none
